# These are supported funding model platforms

# patreon: # Replace with your Patreon username
# ko_fi: # Replace with your Ko-fi username
# open_collective: # Replace with your Open Collective username
# issuehunt: # Replace with your IssueHunt username
custom: [ "https://paypal.me/marcuwynu23" ]
